# version: v1.6.2
# metadata -- add as many key/value pairs as you want
[metadata]
  org = "example.com/${ORG_PATH}/"
  maintainer = "k8s-admin (me@example.com)"
  description = "example Desired State File for demo purposes."


# paths to the certificate for connecting to the cluster
# You can skip this if you use Helmsman on a machine with kubectl already connected to your k8s cluster.
# you have to use exact key names here : 'caCrt' for certificate and 'caKey' for the key and caClient for the client certificate
[certificates]
#  caClient = "gs://mybucket/client.crt" # GCS bucket path
#  caCrt = "s3://mybucket/ca.crt" # S3 bucket path
#  caKey = "/etc/kubernetes/ssl/ca.pem" # valid local file relative path


[settings]
 # kubeContext = "admin-cluster.local" # will try connect to this context first, if it does not exist, it will be created using the details below
 # username = "admin-cluster.local"
#  password = "$K8S_PASSWORD" # the name of an environment variable containing the k8s password
#  clusterURI = "${SET_URI}" # the name of an environment variable containing the cluster API
 # clusterURI = "https://192.168.11.6:6443" # equivalent to the above
  # serviceAccount = "tiller" # k8s serviceaccount. If it does not exist, it will be created.
  # storageBackend = "secret" # default is configMap
#  slackWebhook = "$slack" # or "your slack webhook url"
#  reverseDelete = false # reverse the priorities on delete
#### to use bearer token:
#  bearerToken = true
#  clusterURI = "https://kubernetes.default"



# define your environments and their k8s namespaces
# syntax:
# [namespaces.<your namespace>] -- whitespace before this entry does not matter, use whatever indentation style you like
# protected = <true or false> -- default to false
[namespaces]
  [namespaces.default]
    protected = false


# define any private/public helm charts repos you would like to get charts from
# syntax: repo_name = "repo_url"
# only private repos hosted in s3 buckets are now supported
[helmRepos]
  chartmuseum = "http://admin:advant1cH@${DSS_HOST_IP}:8081"
#  stable = "https://kubernetes-charts.storage.googleapis.com"
#  incubator = "http://storage.googleapis.com/kubernetes-charts-incubator"
#  myS3repo = "s3://my-S3-private-repo/charts"
#  myGCSrepo = "gs://my-GCS-private-repo/charts"
#  custom = "https://user:pass@mycustomrepo.org"


# define the desired state of your applications helm charts
# each contains the following:
[apps]

  # jenkins will be deployed using the Tiller in the staging namespace
  [apps.edgesense]
    namespace = "default" # maps to the namespace as defined in namespaces above
    enabled = true # change to false if you want to delete this app release [default = false]
    chart = "chartmuseum/es-edgesense" # changing the chart name means delete and recreate this release
    version = "1.0.15" # chart version
    ### Optional values below
    name = "es-edgesense" # should be unique across all apps which are managed by the same Tiller
  #  valuesFile = "../Minio/values.yaml" # leaving it empty uses the default chart values
  #  tillerNamespace = "kube-system" # which Tiller to use to deploy this release
    purge = true # will only be considered when there is a delete operation
    test = true # run the tests when this release is installed for the first time only
    protected = true
    priority= 0
    wait = false
  # [apps.jenkins.setString] # values to override values from values.yaml with values from env vars or directly entered-- useful for passing secrets to charts
  #   AdminPassword="$JENKINS_PASSWORD" # $JENKINS_PASSWORD must exist in the environment
  #   MyLongIntVar="1234567890"
  [apps.edgesense.set]
    "quota.portal.resources.limits.memory" = "2Gi"

  [apps.minio]
    namespace = "default" # maps to the namespace as defined in namespaces above
    enabled = true # change to false if you want to delete this app release [default = false]
    chart = "chartmuseum/es-minio" # changing the chart name means delete and recreate this release
    version = "2.3.15" # chart version
    ### Optional values below
    name = "es-minio" # should be unique across all apps which are managed by the same Tiller
  #  valuesFile = "../Minio/values.yaml" # leaving it empty uses the default chart values
  #  tillerNamespace = "kube-system" # which Tiller to use to deploy this release
    purge = true # will only be considered when there is a delete operation
    test = true # run the tests when this release is installed for the first time only
    protected = false
    priority= 0
    wait = false
  # [apps.jenkins.setString] # values to override values from values.yaml with values from env vars or directly entered-- useful for passing secrets to charts
  #   AdminPassword="$JENKINS_PASSWORD" # $JENKINS_PASSWORD must exist in the environment
  #   MyLongIntVar="1234567890"
  [apps.minio.set]
    "resources.limits.memory" = "256Mi"

# See https://github.com/Praqma/helmsman/blob/master/docs/desired_state_specification.md#apps for more apps options
